### PR TITLE
Component should update when className is changed

### PR DESCRIPTION
**Pull request by WendellLiu**
it will make this component flexible to make some style change

### CODE REVIEW

**Comment by Treora** [comment]
Looks good to me, I can't think of cases where this would harm.

As I [wrote][1] yesterday:
> perhaps we should think about a more general way to check for changes in props that are passed through to the element. Should the component perhaps update if any prop has changed, except if our tests find that the change is already reflected in the DOM?

I would suggest to merge this for now, and possibly later we can try out if updating on every prop change not related to `innerHTML` would indeed be an improvement.

[1]: https://github.com/lovasoa/react-contenteditable/pull/30#issuecomment-244032924

**Comment by eugene1g** [comment]
In the same spirit, it would be great to reflect changes in `style` prop as well.

**Comment by monolithed** [comment]
It can be implemented something like:

```ts
{
	shouldComponentUpdate (nextProps) {
		// We need not rerender if the change of props simply reflects the user's
		// edits. Rerendering in this case would make the cursor/caret jump.

		// Rerender if there is no element yet... (somehow?)
		if (!this.htmlEl) {
			return true;
		}

		// ...or if html really changed... (programmatically, not by user edit)
		if (nextProps.html !== this.htmlEl.innerHTML && nextProps.html !== this.props.html) {
			return true;
		}

		let props = Object.entries(this.props);

		// Handle custom properties
		return Array.prototype.some.call(props, ([key, value]) => {
			if (!(value instanceof Object)) {
				return value !== nextProps[key];
			}
		});
	}
}
```

**Comment by ajbeaven** [comment]
Can this be merged please?

**Comment by Treora** [comment]
I get the impression nobody is actively maintaining this project anymore.. Neither am I, but I can still press the merge button if that helps anyone. I am not able to publish a release update however, I guess you may have to kindly poke @lovasoa for that.

**Pull request merged**
