### PR TITLE
add license info to each file

### PR DESCRIPTION
**Pull request by motosuzu**
To lovasoa,

Your react-contenteditable is found to be very valuable asset.
Our corporate service can deliver great value to the world with react-contenteditable.

The Git license seems to be distributed under Apache-2.0 (http://opensource.org/licenses/) listed in OSI.
However, license notation can not be found in each source code of react-contenteditable.
Our service team added licnesed to each files. 

Your contribution is greatly appreciated.
Best Regards.

### CODE REVIEW

**Comment by motosuzu** [comment]
Thank you for your comment.
Could you please confirm.

**Comment by lovasoa** [comment]
You removed the comment manually from the compiled file, but it is regenerated automatically on the next compilation. Running `npm run compile` on a freshly cloned repo shouldn't lead to changes in any file.

You might have to add a babel plugin, but you should always run `npm run compile` before committing anything.

**Comment by motosuzu** [comment]
Thank you for your comment.
I executed ```npm run compile```.
Could you please confirm.

**Comment by lovasoa** [comment]
But now, the licence comment is in the compiled file again.

**Comment by motosuzu** [comment]
Let me make sure one thing; you DO NOT want to add the license code to the compiled file (lib/react-contenteditable.js)?
 
We like to use lib/react-contenteditable.js but it must contain the license code and that's why I'm trying to add the license.

**Comment by lovasoa** [comment]
The compiled file is not meant to be read by humans, I don't really see the interest of making it heavier by adding a license to it. Why would you want to do so?

**Comment by motosuzu** [comment]
Our concern is following...
Our service is intended for vast number of users worldwide. 
Files are accessible to people in public. 
In this case, We want to protect your files from illegal usage because of lack of copyright. So please, allow us to have copy right.

However, as you've concerend, file size may increase.
In order to avoid above, how about adding 2 words(yyyy and your-name) at line 189 of following 1 license file. 
https://github.com/lovasoa/react-contenteditable/blob/master/LICENSE#L189a

Your contribution is really appreciated. 

Kindly Regards.

**Comment by lovasoa** [comment]
Oh, you're right, this is clearly something I forgot to fill in.

**Pull request closed without merging**
