### PR TITLE
Prop to access internal ref

### PR DESCRIPTION
**Pull request by wchaering**
internalRef prop gives access to contenteditable ref

### CODE REVIEW

**Comment by ryanscottaudio** [comment]
what's the status on this PR?

**Comment by richard-bluedot** [comment]
This PR is great. Any chance we can get it merged in? Currently having to query the DOM to get access to the internal div of the component, since FindDOMNode has been deprecated.

**Comment by chardos** [comment]
This PR is great. Any chance we can get it merged in? Currently having to query the DOM to get access to the internal div of the component, since FindDOMNode has been deprecated.

**Comment by chardos** [comment]
Just realised, the internal ref is reachable by getting a reference to the ContentEditable component, then reading its `htmlEl`.

E.g. `<ContentEditable ref={(node) => { this.contentEditable = node }} />`

Then you will have a ref to the element via `this.contentEditable.htmlEl`.

**Pull request closed without merging**
